#ifndef ERRCODE_H
#define ERRCODE_H

#define SUCCESS 0
#define INVALID_FILE -1
#define FILE_NOT_FOUND -2
#define MACRO_NOT_FOUND -3
#define C_COMPILE_ERROR -4
#define BAD_USE_OF_BRACKET -6
#define BAD_USE_OF_PARENTHESIS -7
#define UNKNOWN_DECORATOR -8
#define UNCLOSED_DECORATOR -9
#define ILLEGAL_CHARACTER -10
#define MEMORY_ALLOCATION_FAILED -11
#define FILE_DELETION_FAILED -12
#define FOLDER_CREATION_FAILED -13

#endif