typedef enum {
    INVALID_FILE,
    FILE_NOT_FOUND,
    UNKNOWN_IDENTIFIER,
    UNKNOWN_PROPERTY,
    C_COMPILE_ERROR,
    UNKNOWN_FUNCTION,
    UNKNOWN_DATATYPE,
    INVALID_FILENAME,
    PREDEFINED_VARIABLE,
    INVALID_IMPORT,
    NO_ERROR,
    UNDEFINED_VARIABLE,
    INVALID_VARIABLE,
    ILLEGAL_DATATYPE,
    REPEATED_KEY
} ErrorCode;